import { logger } from '../utils/logger.js';
import type { RemediationConfig } from '../snyk/types.js';

export interface PrDetails {
  title: string;
  body: string;
  head: string;
  base: string;
  labels?: string[];
  reviewers?: string[];
  teamReviewers?: string[];
}

export interface CreatedPr {
  number: number;
  html_url: string;
  title: string;
}

export async function createOrUpdatePr(
  details: PrDetails,
  config: RemediationConfig,
): Promise<CreatedPr | null> {
  if (config.dryRun) {
    logger.info(`[dry-run] Would create PR: "${details.title}" (${details.head} -> ${details.base})`);
    return null;
  }

  const [owner, repo] = config.githubRepository.split('/');
  if (!owner || !repo) {
    throw new Error(`Invalid GITHUB_REPOSITORY: ${config.githubRepository}`);
  }

  // Authorization value is masked in logs by logger.ts maskSecrets()
  const authValue = 'Bearer ' + config.githubToken;
  const headers: Record<string, string> = {
    Authorization: authValue,
    Accept: 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
    'Content-Type': 'application/json',
  };

  const apiBase = 'https://api.github.com';

  // Check if PR already exists from head to base
  const listUrl = `${apiBase}/repos/${owner}/${repo}/pulls?head=${owner}:${details.head}&base=${details.base}&state=open`;
  const listResponse = await fetch(listUrl, { headers });

  if (listResponse.ok) {
    const existing = (await listResponse.json()) as Array<{
      number: number;
      html_url: string;
      title: string;
    }>;
    if (existing.length > 0 && existing[0]) {
      logger.info(`PR already exists: #${existing[0].number} — ${existing[0].html_url}`);
      return {
        number: existing[0].number,
        html_url: existing[0].html_url,
        title: existing[0].title,
      };
    }
  }

  // Create new PR
  const createUrl = `${apiBase}/repos/${owner}/${repo}/pulls`;
  const createResponse = await fetch(createUrl, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      title: details.title,
      body: details.body,
      head: details.head,
      base: details.base,
      draft: false,
    }),
  });

  if (!createResponse.ok) {
    const body = await createResponse.text();
    throw new Error(`Failed to create PR: ${createResponse.status} ${body}`);
  }

  const pr = (await createResponse.json()) as {
    number: number;
    html_url: string;
    title: string;
    node_id: string;
  };

  logger.info(`Created PR #${pr.number}: ${pr.html_url}`);

  // Add labels
  if (details.labels && details.labels.length > 0) {
    await fetch(`${apiBase}/repos/${owner}/${repo}/issues/${pr.number}/labels`, {
      method: 'POST',
      headers,
      body: JSON.stringify({ labels: details.labels }),
    });
  }

  // Add reviewers
  if (
    (details.reviewers && details.reviewers.length > 0) ||
    (details.teamReviewers && details.teamReviewers.length > 0)
  ) {
    await fetch(`${apiBase}/repos/${owner}/${repo}/pulls/${pr.number}/requested_reviewers`, {
      method: 'POST',
      headers,
      body: JSON.stringify({
        reviewers: details.reviewers ?? [],
        team_reviewers: details.teamReviewers ?? [],
      }),
    });
  }

  return { number: pr.number, html_url: pr.html_url, title: pr.title };
}

export function buildPrBody(
  fixedPackages: string[],
  fixedIssueIds: string[],
  targetBranch: string,
): string {
  return `## 🔒 Snyk Security Auto-Remediation

This PR was automatically generated by the **Snyk Auto-Remediation toolkit** to fix security vulnerabilities detected in your dependencies.

### 📦 Changes Made

${fixedPackages.map((p) => `- ${p}`).join('\n')}

### 🐛 Fixed Snyk Findings

${fixedIssueIds.map((id) => `- \`${id}\``).join('\n')}

### 🎯 Target Branch

\`${targetBranch}\`

---

> **Note:** This PR was created automatically. Please review the changes carefully before merging.
> If you have questions or concerns, please comment on this PR.

<!-- snyk-auto-remediation: true -->
`;
}
