import { logger } from '../utils/logger.js';
import type { RemediationConfig } from '../snyk/types.js';
import { GitHubApiClient } from './api-client.js';

export interface PrDetails {
  title: string;
  body: string;
  head: string;
  base: string;
  labels?: string[];
  reviewers?: string[];
  teamReviewers?: string[];
}

export interface CreatedPr {
  number: number;
  html_url: string;
  title: string;
  created: boolean;
}

async function applyPrMetadata(
  client: GitHubApiClient,
  pullNumber: number,
  details: PrDetails,
): Promise<void> {
  if (details.labels?.length) {
    for (const label of details.labels) {
      await client.ensureLabel(label, '6f42c1', 'Snyk remediation workflow label');
    }
    await client.addLabels(pullNumber, details.labels);
  }
  if (details.reviewers?.length || details.teamReviewers?.length) {
    await client.requestReviewers(pullNumber, details.reviewers ?? [], details.teamReviewers ?? []);
  }
}

export async function createOrUpdatePr(
  details: PrDetails,
  config: RemediationConfig,
): Promise<CreatedPr | null> {
  if (config.dryRun) {
    logger.info(
      `[dry-run] Would create or update PR: "${details.title}" (${details.head} -> ${details.base})`,
    );
    return null;
  }
  if (!config.githubToken) throw new Error('GITHUB_TOKEN is required to create or update a PR');

  const client = new GitHubApiClient(config.githubToken, config.githubRepository);
  const existing = (await client.listPulls(details.head, details.base))[0];
  if (existing) {
    const updated = await client.updatePull(existing.number, {
      title: details.title,
      body: details.body,
      base: details.base,
    });
    await applyPrMetadata(client, existing.number, details);
    logger.info(`Updated PR #${updated.number}: ${updated.html_url}`);
    return { ...updated, created: false };
  }

  const created = await client.createPull({
    title: details.title,
    body: details.body,
    head: details.head,
    base: details.base,
    draft: false,
  });
  await applyPrMetadata(client, created.number, details);
  logger.info(`Created PR #${created.number}: ${created.html_url}`);
  return { ...created, created: true };
}

export function buildPrBody(
  fixedPackages: string[],
  fixedIssueIds: string[],
  targetBranch: string,
): string {
  return `## 🔒 Snyk Security Auto-Remediation

This PR was automatically generated by the **Snyk Auto-Remediation toolkit** to fix security vulnerabilities detected in your dependencies.

### 📦 Changes Made

${fixedPackages.map((item) => `- ${item}`).join('\n')}

### 🐛 Fixed Snyk Findings

${fixedIssueIds.map((id) => `- \`${id}\``).join('\n')}

### 🎯 Target Branch

\`${targetBranch}\`

---

> **Note:** This PR was created automatically. Please review the changes carefully before merging.

<!-- snyk-auto-remediation: true -->
`;
}
