import { appendFileSync } from 'fs';
import type { RemediationReport } from '../snyk/types.js';
import { logger } from '../utils/logger.js';

export function buildMarkdownSummary(report: RemediationReport): string {
  const lines: string[] = [
    `# 🔒 Snyk Auto-Remediation Summary`,
    '',
    `> **Repository:** \`${report.repository}\`  `,
    `> **Target Branch:** \`${report.targetBranch}\`  `,
    `> **Run Timestamp:** ${report.timestamp}  `,
    `> **Severity Threshold:** \`${report.severityThreshold}\`  `,
    `> **Dry Run:** ${report.dryRun ? '✅ Yes' : '❌ No'}  `,
    '',
    '## 📊 Summary',
    '',
    '| Metric | Count |',
    '|--------|-------|',
    `| Total Findings | ${report.totalFindings} |`,
    `| Fixable Findings | ${report.fixableFindings} |`,
    `| Successfully Fixed | ${report.fixedFindings} |`,
    `| Findings Requiring Fallback | ${report.unfixableFindings} |`,
    `| PRs Created | ${report.prsCreated} |`,
    `| GitHub Issues Created | ${report.issuesCreated} |`,
    `| GitHub Issues Updated | ${report.issuesUpdated} |`,
    `| GitHub Issues Closed | ${report.issuesClosed} |`,
    `| GitHub Issues Planned | ${report.issuesPlanned} |`,
    '',
  ];

  if (report.fixResults.length > 0) {
    lines.push('## 🛠 Fix Results by Package Manager', '');
    for (const result of report.fixResults) {
      const status = result.success ? '✅' : '❌';
      lines.push(`### ${status} ${result.packageManager}`);
      lines.push('');
      if (result.changesApplied.length > 0) {
        lines.push('**Changes Applied:**');
        for (const change of result.changesApplied) {
          lines.push(`- ${change}`);
        }
        lines.push('');
      }
      if (result.error) {
        lines.push(`**Error:** ${result.error}`, '');
      }
      if (result.failedFindings.length > 0) {
        lines.push(`**Failed to fix ${result.failedFindings.length} finding(s)**`, '');
      }
    }
  }

  if (report.errors.length > 0) {
    lines.push('## ⚠️ Errors', '');
    for (const error of report.errors) {
      lines.push(`- ${error}`);
    }
    lines.push('');
  }

  lines.push('---', '');
  lines.push(
    `*Generated by [Snyk Auto-Remediation Toolkit](https://github.com/uppnrise/snyk-auto-remediate)*`,
  );

  return lines.join('\n');
}

export function writeStepSummary(report: RemediationReport): void {
  const summaryFile = process.env['GITHUB_STEP_SUMMARY'];
  if (!summaryFile) {
    logger.debug('GITHUB_STEP_SUMMARY not set — skipping step summary');
    return;
  }

  const summary = buildMarkdownSummary(report);
  try {
    appendFileSync(summaryFile, summary, 'utf-8');
    logger.info('GitHub step summary written');
  } catch (error) {
    logger.warn(`Could not write step summary: ${String(error)}`);
  }
}
